### ISSUE TITLE
Translating content structures

### ISSUE THREAD

**Issue by fsuter** [derhansen/sf_tv2fluidge#102]
I have just started trying out this extension and it works great. I'm just wondering about how FCEs are handled in multilingual web sites. Maybe this extension covers my use case and I just didn't check the right option.

So here's my use case:

We have various FCEs like 2-column, 3-column, etc. structures. The way we generally use them is that we set the FCE itself to "All" languages and translate the content elements inside each column.

What happened as my result of using "sf_tv2fluidge" (and I may have done the wrong thing) is that my FCEs are moved to their Grid elements equivalent only in the default language. The contents of the columns are translated, but since the container itself is not, nothing appears in the pages (and, obviously, the translated content elements don't look as if they are part of any container in the backend).

Is that some wrong usage of my part or is it a shortcoming of "sf_tv2fluidge" in its current state? If the latter, I will probably take a look at extending it since this is a feature that we will badly need.

**Comment by derhansen** [comment]
Its been a while I've migrated my last TemplaVoila site with the extension, so I made a test in my TYPO3 test installation.

My test installation has a 2 column FCE, where I set the language to "All". It contains 2 content elements, which are both translated to another language. I think this matches your scenario and this was also always the way I used to work with TemplaVoila an multilingual sites.

Next I processed the following steps:

1. Delete unused Elements 
2. Convert references 
3. Migrate FCE Migrate content 
4. Convert Grid Elements

The last step is the important one (I just left all settings to their defaults). It created copies of the migrated Grid Element to all existing languages and reassigns all translated content elements to the newly created (and translated) Grid Element. 

The result after the migration should look as shown on the screenshot below

![bildschirmfoto 2016-02-09 um 20 07 13](https://cloud.githubusercontent.com/assets/2629896/12927496/d5e0dd92-cf68-11e5-9447-bd168e4c4e2f.png)

The original FCE looked as following

![bildschirmfoto 2016-02-09 um 20 10 11](https://cloud.githubusercontent.com/assets/2629896/12927583/2ba50a6e-cf69-11e5-9b4e-db1b8c1e72a8.png)

The manual also contains some more information about the migration process for FCE with language set to all: https://github.com/derhansen/sf_tv2fluidge#convert-gridelements-with-language-set-to-all-languages

I recommend to use the latest version from GitHub (master branch is ok), since it contain some small bugfixes due to PHP 5.6 compatibility.

Hope this helps

**Comment by fsuter** [comment]
Hi Torben,

Thanks a lot for your detailed answer, I appreciate it very much. I'm not exactly sure when I will have time to check on this migration again, but I'll make sure to check back here and close the issue if everything works fine.

**Comment by fsuter** [comment]
Hi Torben,

I could test again and it worked. Much to my surprise and shame, I realised that not all FCEs were in "All" language as I had thought, which explains the problems I had (maybe also switching from TER version to Git master helped in some cases).

Could you maybe clarify the options in the "Convert GridElements" module? I have tried various combinations and got the same results no matter what... I also don't understand what you mean by "language shortcuts".

**Comment by derhansen** [comment]
Hi François,

I believe that the "language shortcuts" are references to "All language" elements. Some parts of the "Convert Grid Elements" module are not written by me (especially the options you mean). Andreas Allacher was working on that part of the module and had some use cases, where he needed those options for some special cases (e.g. referenced element has no default translation). Some of those options are described in the PRs from Andreas (e.g. https://github.com/derhansen/sf_tv2fluidge/pull/88), but never made it into the manual as I never used them. 

Best regards
Torben

**Comment by fsuter** [comment]
Thanks for your answer. I'll see of those options turn out to be useful for me too in future use cases. For now, my migration is done :-)

Thanks again for your help.
