### ISSUE TITLE
[FEATURE] Add support for migration from templavoilaplus

### ISSUE THREAD

**Issue by Outdoorsman** [derhansen/sf_tv2fluidge#112]
**Would it be crazy hard to make this extension (or a fork of it) work for `templavoilaplus`?** I have used the `templavoilaplus` migration tool to migrate from `templavoila` but there are certainly people who need to change templating systems for one reason or another to `gridelements`. 

I have converted a number of client websites to `templavoilaplus` and now enough content changes have happened that I can't go back and I know I'm not the only one in that boat.

Thoughts anyone?

**Comment by derhansen** [comment]
`templavoilaplus` contain a lot of refactorings and a fork of `sf_tv2fluidge` should be made compatible to respect the changes in `templavoilaplus`. 

I managed to get the `sf_tv2fluidge` backend module to show up, but some migrations fail due to changes in the data structure. So I expect, a compatible version would require a lot of debugging work and it has to be noted, that the original version of `sf_tv2fluidge` in some cases (depending on the TV site setup) also required special changes, which I adopted for each migration project individually.

I will not really have the time for this task, so if you are not able to make the modification in a fork yourself, you could try to to contact Gernot Ploiner, who offers a commercial TV migration service -
 see: http://tvconverter.webprofil.at/

**Comment by Outdoorsman** [comment]
Thank you @derhansen for taking the time to comment about `templavoilaplus`... that was very helpful so I know how to proceed.
