### ISSUE TITLE
Make work with Typo3 7?

### ISSUE THREAD

**Issue by subnoodle** [derhansen/sf_tv2fluidge#117]
Dear Torben,

latley you helped with a new Extractor-release...
Now, there a project with Typo3 7 and Templavoila PLUS.
Can you please give a clue what it would take to make this extension work with Typo3 7 and Templavoila PLUS?

Thank you very much,

Thomas

**Comment by derhansen** [comment]
Hello Thomas,

the extension did never work for TYPO3 7.6, since there was no working version of ext:templavoila that could be used. I also never tested the extension with ext:templavoilaplus, so I can not say if it would work or not. 

If you habe PHP / templavoila data structure knowlege, you can try to make the extension work with ext:templavoilaplus. If this is no option for you, you can try to contact the makers of https://tvconverter.webprofil.at/de/ and ask if their converter is able to migrate from ext:templavoilaplus

**Comment by derhansen** [comment]
I'm closing the issue, since ext:templavoilaplus is not supported by sf_tv2fluidge

**Comment by subnoodle** [comment]
Dear Hansen, thank you for your polite hints.
All best, Th.
