### ISSUE TITLE
question regarding CLI support

### ISSUE THREAD

**Issue by kaystrobach** [derhansen/sf_tv2fluidge#98]
Hello @derhansen,

after checking out your plugin (what i really like) I would like to ask 2 question (maybe I can also provide a PR for that :smile: )
## please add a commandline interface

at rather big sites it's totally risky to migrate all the content via a webinterface, so i would like to have a mode, which indicates a joblist (e.g. in a yaml file) where all the migrations and mappings can be specified.
To aid the user the backend module we have now could display the configuration in the step before the execution.
## migration von TVFramework to THEMES

having the CLI Interface it would be easy to migrate from TVFramework to THEMES with just some smart steps ;) like a predefined commandline call wait some minutes and you are done ;)

Thanks a lot for your work - would love to get some feedback on my thoughts

**Comment by derhansen** [comment]
Hello Kay,

I really like the idea of providing CLI support for all modules of the extension. Since nearly all migration routines are decoupled as a service, it should at least be possible to create some command controllers, that make use of the services without breaking stuff. YAML seems to be a reasonable way to configure command line migrations.

I'll assign this feature request to myself and will update it, as soon as I begin with the implement CLI support. At the moment I can't give an time estimate when this will happen, but I hope I will get some free time slots in the next weeks. Of course PRs are always welcome :-)

**Comment by mario-naether** [comment]
Hallo @derhansen @kaystrobach ,

I had add the CLI Support in my forked "command" branch.
https://github.com/mario-naether/sf_tv2fluidge/tree/command
This works where well!
This branch workes also with TYPO3 7.6.

**Comment by derhansen** [comment]
Thanks for your work @mario-naether

I'm pretty sure I will use some of your changes in future versions of the extension

**Comment by derhansen** [comment]
CLI support has been merged. Thanks!

**Comment by kaystrobach** [comment]
@derhansen i think the pure cli support is just the first step, next step is the "run from generated configuration" stuff, like use the UI to define what has to be migrated how, then execute the migration from a control file
